### ISSUE TITLE
Bring mono changes upstream

### ISSUE THREAD

**Issue by roblillack** [roblillack/monoberry#7]
This would reduce the cost of maintaining MonoBerry tremendously. A list of the current patches is here: https://github.com/roblillack/mono/compare/mono:mono-3.2.4...qnx-3.2.4

**Comment by fabzter** [comment]
so is this really dead? :(

**Comment by roblillack** [comment]
Realizing that it's been a year since I last worked on MonoBerry, you can can probably say so.

I'm fully stretched with so many other commitments, that I cannot invest any time here, right now. If you'd like to take over or help in any way: Go ahead. :+1:
